# Generated by Django 5.2.11 on 2026-02-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="bodyweight",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="is_pr",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workout",
            name="mood",
            field=models.CharField(
                blank=True,
                choices=[
                    ("terrible", "Terrible"),
                    ("bad", "Bad"),
                    ("ok", "Ok"),
                    ("good", "Good"),
                    ("great", "Great"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="program_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="workout",
            name="sleep_hours",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
