# Generated by Django 5.2.11 on 2026-03-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0002_workout_bodyweight_workout_is_pr_workout_mood_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workout",
            name="is_pr",
            field=models.BooleanField(default=False),
        ),
    ]
