# Generated by Django 5.2.11 on 2026-03-02 16:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def assign_existing_tags_to_users(apps, schema_editor):
    Tag = apps.get_model("workouts", "Tag")
    Workout = apps.get_model("workouts", "Workout")
    through_model = Workout.tags.through
    db_alias = schema_editor.connection.alias

    for tag in Tag.objects.using(db_alias).all().order_by("id"):
        workout_pairs = list(
            Workout.objects.using(db_alias)
            .filter(tags=tag)
            .values_list("id", "user_id")
            .order_by("id")
        )

        workouts_by_user = {}
        for workout_id, user_id in workout_pairs:
            if user_id is None:
                continue
            workouts_by_user.setdefault(user_id, []).append(workout_id)

        user_ids = list(workouts_by_user.keys())
        if not user_ids:
            continue

        tag.user_id = user_ids[0]
        tag.save(update_fields=["user"])

        for user_id in user_ids[1:]:
            cloned_tag = Tag.objects.using(db_alias).create(name=tag.name, user_id=user_id)
            through_model.objects.using(db_alias).filter(
                workout_id__in=workouts_by_user[user_id],
                tag_id=tag.id,
            ).update(tag_id=cloned_tag.id)


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0003_alter_workout_is_pr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="tag",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exerciseentry",
            name="rpe",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("10.0")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="exerciseentry",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=6,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(
            assign_existing_tags_to_users, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="workout",
            name="bodyweight",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.0"))],
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="duration_minutes",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(1440)]
            ),
        ),
        migrations.AlterField(
            model_name="workout",
            name="sleep_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.0")),
                    django.core.validators.MaxValueValidator(Decimal("24.0")),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_user_tag_name"
            ),
        ),
    ]
